import dotenv from "dotenv";

dotenv.config();

const BLUEBIRD_LOGISTIC_API_BASE_URL =
  process.env.BLUEBIRD_LOGISTIC_API_BASE_URL || "";
const BLUEBIRD_LOGISTIC_API_TOKEN_URL = `${BLUEBIRD_LOGISTIC_API_BASE_URL}/logistic/connect/token`;
const BLUEBIRD_LOGISTIC_API_ORDER_URL = `${BLUEBIRD_LOGISTIC_API_BASE_URL}/logistic/order`;
const BLUEBIRD_LOGISTIC_API_ORDER_V2_URL = `${BLUEBIRD_LOGISTIC_API_BASE_URL}/logistic/v2/order`;
const BLUEBIRD_LOGISTIC_API_ORDER_V3_URL = `${BLUEBIRD_LOGISTIC_API_BASE_URL}/logistic/v3/order`;
const BLUEBIRD_LOGISTIC_API_FARE_URL = `${BLUEBIRD_LOGISTIC_API_BASE_URL}/logistic/price/estimated `;

const BLUEBIRD_LOGISTIC_API_CLIENT_ID =
  process.env.BLUEBIRD_LOGISTIC_API_CLIENT_ID || "";
const BLUEBIRD_LOGISTIC_API_CLIENT_SECRET =
  process.env.BLUEBIRD_LOGISTIC_API_CLIENT_SECRET || "";

export {
  BLUEBIRD_LOGISTIC_API_BASE_URL,
  BLUEBIRD_LOGISTIC_API_TOKEN_URL,
  BLUEBIRD_LOGISTIC_API_ORDER_URL,
  BLUEBIRD_LOGISTIC_API_ORDER_V2_URL,
  BLUEBIRD_LOGISTIC_API_ORDER_V3_URL,
  BLUEBIRD_LOGISTIC_API_FARE_URL,
  BLUEBIRD_LOGISTIC_API_CLIENT_ID,
  BLUEBIRD_LOGISTIC_API_CLIENT_SECRET,
};
