const { DataTypes } = require("sequelize");
const sequelize = require("../config/db");

const Customer = sequelize.define(
  "Customer",
  {
    id: {
      type: DataTypes.INTEGER.UNSIGNED,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false,
    },
    name: DataTypes.STRING,
    email: DataTypes.STRING,
    password: DataTypes.STRING,
    phone: DataTypes.STRING,
    gender: DataTypes.STRING(7),
    cust_status: DataTypes.STRING,
    status_log: DataTypes.TEXT,
    mou_status: DataTypes.STRING,
    notes: DataTypes.TEXT,
    npwp: DataTypes.STRING,
    nik: DataTypes.STRING,
    ktp_img: DataTypes.TEXT,
    npwp_img: DataTypes.TEXT,
    address: DataTypes.TEXT("medium"),
    type: DataTypes.INTEGER,
    refcode: DataTypes.STRING(15),
    company_type: DataTypes.INTEGER.UNSIGNED,
    company_name: DataTypes.STRING,
    company_address: DataTypes.TEXT,
    company_email: DataTypes.STRING,
    company_phone: DataTypes.STRING,
    points: DataTypes.DOUBLE(20, 2),
    device_type: DataTypes.STRING(100),
    device_os: DataTypes.STRING(100),
    customer_settings: DataTypes.STRING,
    credits: DataTypes.DOUBLE(20, 2),
    label: DataTypes.TEXT,
    owner: DataTypes.INTEGER.UNSIGNED,
    deleted_at: DataTypes.DATE,
    google_id: DataTypes.TEXT,
    avatar: DataTypes.TEXT,
    avatar_original: DataTypes.TEXT,
    is_member: DataTypes.INTEGER,
    member_since: DataTypes.DATE,
    no_finance: DataTypes.STRING(100),
    no_finance_2: DataTypes.STRING(100),
    invoice_address: DataTypes.TEXT,
    is_ba: DataTypes.INTEGER,
    my_referral_code: DataTypes.STRING(191),
    upline_referral_code: DataTypes.STRING(191),
    // _lft: DataTypes.INTEGER.UNSIGNED,
    // _rgt: DataTypes.INTEGER.UNSIGNED,
    _lft: {
      type: DataTypes.INTEGER.UNSIGNED,
      field: "_lft", // explicitly map to DB column
    },
    _rgt: {
      type: DataTypes.INTEGER.UNSIGNED,
      field: "_rgt",
    },
    parent_id: DataTypes.INTEGER.UNSIGNED,
    wp_id: DataTypes.INTEGER,
    application_letter: DataTypes.TEXT,
    login: DataTypes.INTEGER,
    fbasekey: DataTypes.STRING,
    google_sso: DataTypes.STRING,
    reset_password: DataTypes.STRING(12),
    verified: DataTypes.INTEGER,
    invoice_tax_status: DataTypes.INTEGER,
    is_staging: DataTypes.INTEGER,
    ep_join_date: DataTypes.DATE,
    avatar_image: DataTypes.TEXT,
    verified_token: DataTypes.STRING(12),
    bank: DataTypes.STRING(20),
    account_number: DataTypes.INTEGER,
    account_name: DataTypes.STRING(50),
    notif_status_pemesanan_produk: DataTypes.INTEGER,
    notif_status_pembayaran: DataTypes.INTEGER,
    notif_penggunaan_point: DataTypes.INTEGER,
    notif_downline_baru: DataTypes.INTEGER,
    notif_point_downline: DataTypes.INTEGER,
    sso: DataTypes.INTEGER,
    verify_email_expired_date: DataTypes.DATE,
    layer: DataTypes.INTEGER,
    program: DataTypes.INTEGER,
    mgm: DataTypes.INTEGER,
    finance_phone_mou: DataTypes.STRING(15),
    mou_docs: DataTypes.STRING,
    mou_type: DataTypes.INTEGER,
    mgm_downline_id: DataTypes.INTEGER,
    finance_phone_mgm: DataTypes.STRING(15),
    approval_mou_operation: DataTypes.INTEGER,
    approval_mou_finance: DataTypes.INTEGER,
    approval_mgm_operation: DataTypes.INTEGER,
    approval_mgm_finance: DataTypes.INTEGER,
    log_program: DataTypes.TEXT,
    log_mou: DataTypes.TEXT,
    mou_end_date: DataTypes.DATE,
    mgm_upline_id: DataTypes.INTEGER,
    uuid: DataTypes.STRING(100),
    level: DataTypes.INTEGER,
    redeemed_points: DataTypes.DOUBLE(20, 2),
  },
  {
    tableName: "customer",
    createdAt: "created_at",
    updatedAt: "updated_at",
    deletedAt: "deleted_at",
    timestamps: true, // handles created_at and updated_at
    paranoid: true, // handles deleted_at
    underscored: true, // snake_case columns
  }
);

module.exports = Customer;
