const { DataTypes } = require("sequelize");
const sequelize = require("../config/db");

const OrderItems = sequelize.define(
  "OrderItems",
  {
    id: {
      type: DataTypes.INTEGER.UNSIGNED,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false,
    },
    assignment: { type: DataTypes.INTEGER.UNSIGNED },
    created_at: { type: DataTypes.DATE },
    updated_at: { type: DataTypes.DATE },
    deleted_at: { type: DataTypes.DATE },
    order_id: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false },
    product_id: { type: DataTypes.INTEGER, allowNull: false },
    name: { type: DataTypes.STRING(191), allowNull: false },
    price: { type: DataTypes.DOUBLE(10, 2), allowNull: false },
    capital_price: {
      type: DataTypes.DOUBLE(10, 2),
      allowNull: false,
      defaultValue: 0.0,
    },
    qty: { type: DataTypes.DOUBLE, allowNull: false },
    bought: { type: DataTypes.DOUBLE, defaultValue: 0 },
    image: { type: DataTypes.TEXT("long"), allowNull: false },
    product_code: { type: DataTypes.STRING(191), allowNull: false },
    subtotal: {
      type: DataTypes.DOUBLE(12, 2),
      allowNull: false,
      defaultValue: 0.0,
    },
    shipping_cost: { type: DataTypes.DOUBLE(10, 2), defaultValue: 0.0 },
    shipping_expedition: { type: DataTypes.STRING(191) },
    shipping_expedition_note: { type: DataTypes.STRING(255) },
    shipping_address: { type: DataTypes.TEXT("long") },
    sender_name: { type: DataTypes.STRING(191) },
    greetings: { type: DataTypes.TEXT("long") },
    receiver_name: { type: DataTypes.STRING(191) },
    receiver_phone: { type: DataTypes.STRING(191) },
    notes: { type: DataTypes.TEXT("long") },
    notes_internal: { type: DataTypes.TEXT("medium"), allowNull: false },
    occasion: { type: DataTypes.STRING(20), allowNull: false },
    city: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false },
    country: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false },
    province: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false },
    date_time: { type: DataTypes.DATE, allowNull: false },
    checked: { type: DataTypes.TEXT, allowNull: false },
    problem: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    fu_er: { type: DataTypes.INTEGER },
    order_status: { type: DataTypes.STRING(50) },
    is_staging: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0,
    },
    track_order_logs: { type: DataTypes.TEXT("long") },
    shipping_express: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0,
    },
    refund_status: { type: DataTypes.INTEGER },
    price_after_refund: { type: DataTypes.DOUBLE(10, 2) },
    special_request_image: { type: DataTypes.TEXT("long") },
    special_request_logo: { type: DataTypes.TEXT("long") },
    receiver_longitude: { type: DataTypes.STRING(100), defaultValue: "0" },
    receiver_latitude: { type: DataTypes.STRING(100) },
    auto_po: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    district: { type: DataTypes.STRING(255) },
    id_district: { type: DataTypes.INTEGER },
    sub_district: { type: DataTypes.STRING(255) },
    id_sub_district: { type: DataTypes.INTEGER },
    product_type: { type: DataTypes.STRING(255) },
    po_type: { type: DataTypes.INTEGER },
    shipping_method: { type: DataTypes.INTEGER },
    address_type: { type: DataTypes.INTEGER },
    pickup_lat: { type: DataTypes.DECIMAL(9, 6) },
    pickup_long: { type: DataTypes.DECIMAL(9, 6) },
    shipping_cost_by_estimation: { type: DataTypes.DOUBLE(10, 2) },
    marked_up_shipping_cost: { type: DataTypes.DOUBLE(10, 2) },
    assembly_cost: { type: DataTypes.DOUBLE(10, 2) },
    express_fee: { type: DataTypes.DOUBLE(10, 2) },
    greetings_card: { type: DataTypes.TEXT },
    on_time_delivery: { type: DataTypes.TINYINT },
  },
  {
    tableName: "order_items",
    createdAt: "created_at",
    updatedAt: "updated_at",
    deletedAt: "deleted_at",
    timestamps: true, // handles created_at and updated_at
    paranoid: true, // handles deleted_at
    underscored: true, // snake_case columns
  }
);

module.exports = OrderItems;
