const { DataTypes } = require("sequelize");
const sequelize = require("../config/db");

const PurchaseOrder = sequelize.define(
  "PurchaseOrder",
  {
    id: {
      type: DataTypes.INTEGER.UNSIGNED,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false,
    },
    created_at: DataTypes.DATE,
    updated_at: DataTypes.DATE,
    supplier_id: DataTypes.INTEGER.UNSIGNED,
    order_id: DataTypes.INTEGER.UNSIGNED,
    customer_id: DataTypes.INTEGER,
    pr_id: DataTypes.INTEGER.UNSIGNED,
    app: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
    },
    app_assign: DataTypes.DATE,
    app_payreq: DataTypes.DATE,
    country: DataTypes.INTEGER.UNSIGNED,
    province: DataTypes.INTEGER.UNSIGNED,
    city: DataTypes.INTEGER.UNSIGNED,
    owner: DataTypes.INTEGER.UNSIGNED,
    product_name: DataTypes.STRING,
    product_code: DataTypes.STRING,
    image: DataTypes.TEXT("long"),
    qty: DataTypes.INTEGER,
    capital_price: DataTypes.DOUBLE(10, 2),
    real_price: DataTypes.DOUBLE(12, 2),
    total: DataTypes.DOUBLE(12, 2),
    amount_after_problem: DataTypes.DOUBLE(10, 2),
    sender_name: DataTypes.STRING,
    sender_phone: DataTypes.STRING,
    receiver_name: DataTypes.STRING,
    receiver_phone: DataTypes.STRING,
    greetings: DataTypes.TEXT("long"),
    shipping_address: DataTypes.TEXT("long"),
    date_time: DataTypes.DATE,
    notes: DataTypes.TEXT("long"),
    real_image: DataTypes.TEXT("long"),
    status: DataTypes.STRING,
    payment_status: DataTypes.STRING,
    payment_type: DataTypes.STRING(25),
    warehouse_expedition: DataTypes.STRING,
    shipper_order_id: DataTypes.STRING,
    courier_phone: DataTypes.STRING,
    shipped_date: DataTypes.DATE,
    tax_invoice_date: DataTypes.DATE,
    tracking_number: DataTypes.STRING,
    shipping_expedition: DataTypes.STRING,
    delivery_receipt: DataTypes.TEXT("long"),
    delivery_location: DataTypes.TEXT("long"),
    deleted_at: DataTypes.DATE,
    status_log: DataTypes.TEXT("long"),
    shipping_cost: DataTypes.DOUBLE(10, 2),
    reason: DataTypes.TEXT("long"),
    due_date: DataTypes.DATE,
    payment_date: DataTypes.DATE,
    payment_notes: DataTypes.TEXT("long"),
    real_image_late: DataTypes.INTEGER,
    shipping_receipt_image_late: DataTypes.INTEGER,
    product_id: DataTypes.INTEGER.UNSIGNED,
    sales_rating: { type: DataTypes.INTEGER, defaultValue: 0 },
    report_rating: { type: DataTypes.INTEGER, defaultValue: 0 },
    shipping_rating: { type: DataTypes.INTEGER, defaultValue: 0 },
    flower_rating: { type: DataTypes.INTEGER, defaultValue: 0 },
    complaint_notes: DataTypes.TEXT("long"),
    complaint_resolution: DataTypes.TEXT("long"),
    resolution_status: DataTypes.STRING(191),
    resolution_check: DataTypes.STRING(191),
    resolution_complaint: DataTypes.STRING(191),
    resolution_admin: { type: DataTypes.INTEGER.UNSIGNED, defaultValue: 0 },
    over_pricing_notes: DataTypes.TEXT("long"),
    general_notes: DataTypes.TEXT("long"),
    notes_internal: DataTypes.TEXT("medium"),
    controller_notes: DataTypes.TEXT("long"),
    revision: DataTypes.INTEGER,
    photo_approval: DataTypes.STRING(25),
    photo_approval_notes: DataTypes.TEXT("long"),
    real_image_revision: DataTypes.TEXT("long"),
    delivery_location_revision: DataTypes.TEXT("long"),
    delivery_receipt_revision: DataTypes.TEXT("long"),
    photo_revision_notes: DataTypes.TEXT("long"),
    approve_image_result: DataTypes.INTEGER,
    approve_image_location: DataTypes.INTEGER,
    approve_delivery_order: DataTypes.INTEGER,
    hp_type: DataTypes.STRING(4),
    revision_image: DataTypes.INTEGER,
    revision_image_log: DataTypes.TEXT("long"),
    approved_payment: DataTypes.INTEGER,
    approved_payment_notes: DataTypes.TEXT("long"),
    resolution_logs: DataTypes.TEXT("long"),
    photo_approval_logs: DataTypes.TEXT("long"),
    photo_revision_logs: DataTypes.TEXT("long"),
    real_image_approval: DataTypes.INTEGER,
    photo_rev_counter: DataTypes.INTEGER,
    app_revision_logs: DataTypes.TEXT("long"),
    finish_time: DataTypes.DATE,
    recomendation_logs: DataTypes.TEXT("long"),
    action_recomendation_logs: DataTypes.TEXT("long"),
    count_search_logs: DataTypes.STRING(5),
    action_search_logs: DataTypes.TEXT("long"),
    pushnotif_counter: DataTypes.TEXT("long"),
    auto_po: { type: DataTypes.INTEGER, defaultValue: 0 },
    wa_rating_point: DataTypes.INTEGER,
    wa_rating_note: DataTypes.STRING,
    po_blast_status: { type: DataTypes.INTEGER, defaultValue: 0 },
    po_blast_time: DataTypes.DATE,
    delivery_location_unconfirmed: DataTypes.INTEGER,
    delivery_location_unconfirmed_index: DataTypes.INTEGER,
    capital_price_reason: DataTypes.STRING,
    po_type: DataTypes.INTEGER,
    shipping_method: DataTypes.INTEGER,
    address_type: DataTypes.INTEGER,
    pickup_lat: DataTypes.DECIMAL(9, 6),
    pickup_long: DataTypes.DECIMAL(9, 6),
    pickup_date: DataTypes.DATE,
  },
  {
    tableName: "purchase_order",
    createdAt: "created_at",
    updatedAt: "updated_at",
    deletedAt: "deleted_at",
    timestamps: true, // handles created_at and updated_at
    paranoid: true, // handles deleted_at
    underscored: true, // snake_case columns
  }
);

module.exports = PurchaseOrder;
